### ISSUE TITLE
KD is calculated incorrectly

### ISSUE THREAD

**Issue by joelwharrison** [dgiling/BEDILM#1]
It appears that KD is calculated incorrectly.  The vertical attenuation coefficient for PAR (KD) is calculated (in Section 3.1) as the slope from the regression:

light.model <- lm(log(e[non0]+1)~meas.depths[non0])

Presumably the +1 is included to avoid taking the log of zero (though this is unnecessary as zeroes are already filtered out by subsetting with [non0]).  However, this gives an incorrect result for KD, biasing the estimate downward - this is not noticeable for a shallow water column, but is a problem if the water column is deep.

Below is an R script that should make the issue clear.

E0 <- 2000
kd_actual <- 0.25

z_max <- 50
z <- c(1:z_max)

Ez <- E0 * exp(-1 * kd_actual * z)
plot(z ~ Ez, ylim = c(z_max,0))

reg <- lm(log(Ez + 1) ~ z)
kd_calcd <- abs(round(reg$coefficients[2], 2))
kd_calcd == kd_actual

z_eu_actual <- 4.60517 / kd_actual
z_eu_calcd <- 4.60517 / kd_calcd

abline(h = z_eu_actual, col = 2)
abline(h = z_eu_calcd, col = 4)

**Comment by dgiling** [comment]
Hi @joelwharrison 
You are correct, thanks for finding this error and providing the example. It's been fixed.
