### ISSUE TITLE
K600, Ks units of m/h not cm/h ?

### ISSUE THREAD

**Issue by joelwharrison** [dgiling/BEDILM#3]
The BEDLIM manual (pg. 7) lists units of cm/h for Ks and no units for K600.  Should units be m/h for both?  Ks is in m/h in Giling et al. 2017a (in L&O).  

In the code, K600 appears to be converted to m/h from cm/h (i.e., divided by 100) where it is calculated on line 365:

 k600[i] <- (2.07 + 0.215*(U10[i]^1.7))/100

**Comment by dgiling** [comment]
Yes, thanks for pointing out this oversight
